package com.example.mentalhealth.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DBRef;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Represents a patient appointment.
 * It contains the patient's name, the doctor (as a reference), appointment date/time, and status.
 */
@Document(collection = "appointments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Appointment {
    @Id
    private String id;  // Unique appointment ID generated by MongoDB.

    private String patientName;  // Who booked the appointment.

    @DBRef
    private Doctor doctor;  // The doctor for this appointment.

    private LocalDateTime appointmentDate;  // When the appointment is scheduled.

    private AppointmentStatus status;  // Current status of the appointment.

    // Define the possible statuses.
    public enum AppointmentStatus {
        PENDING,    // Waiting for the doctor to decide.
        APPROVED,   // The doctor approved the appointment.
        DECLINED    // The doctor declined the appointment.
    }
}
